### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by Kageetai** [gummesson/gulp-pandoc#5]
Hi there,
I just wanted to try this out to create a PDF file, but I get an unspecified error:
```shell
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Transform.emit (events.js:87:13)
    at Transform.onerror (d:\Development\Maap\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:558:12)
    at Transform.emit (events.js:107:17)
    at Transform.<anonymous> (d:\Development\Maap\node_modules\gulp-pandoc\index.js:38:14)
    at ChildProcess.<anonymous> (d:\Development\Maap\node_modules\gulp-pandoc\node_modules\pdc\pdc.js:63:14)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```
HTML creation works fine though...

**Comment by Kageetai** [comment]
Oh yeah and here is my task for that:
```javascript
gulp.src(content_dir+'/*.md')
      .pipe(pandoc({
        from: 'markdown',
        to: 'html5',
        ext: '.html',
        args: ['--smart']
      }))
      .pipe(gulp.dest('dist/'));
    connect.reload();
```

**Comment by JanisE** [comment]
Did you work it out in the end? I got a similar error at one point, but it was because I had set a format argument within the "args" property. Also, the `connect.reload();` part does not relate to the particular task, I suppose.

**Comment by Kageetai** [comment]
No, I switched to gulp-shell to have more controll anyway. And yes, the `connect.reload()` was for browsersync
